name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: Install backend dependencies
        run: npm install

      - name: Lint backend
        run: npm run lint

      - name: Test backend
        run: npm run test
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./frontend

      - name: Lint frontend
        run: npm run lint
        working-directory: ./frontend

      - name: Test frontend
        run: npm run test
        working-directory: ./frontend

      - name: Build frontend
        run: npm run build
        working-directory: ./frontend

  deploy:
    needs: lint_and_test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to FLy.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{secrets.FLY_API_TOKEN}}